### ISSUE TITLE
Ekg fails silently

### ISSUE THREAD

**Issue by k-bx** [tibbe/ekg#40]
Currently, EKG's `forkServer` just uses `forkIO` underneath, but this might (and just did) lead to a situation when EKG process has some uncaught error, and just dies silently.

I propose to use `SlaveThread.fork` instead of `forkIO`. It would re-raise exception, so it would be up to EKG's user to catch&ignore it or not (and maybe re-start EKG).

Bad part of this solution would be that it might be that some people are OK if ekg failed silently, while they would certainly not expect any exception from it, so consequences might be quite bad for them (app-stop, for example).

That's why another option is to add catching of all exceptions in `forkServer` (via `enclosed-exceptions.catchAny`), and to restart ekg infinitely on error, and provide new piece of API, like `forkServerThrowing`, which would throw exceptions on error and not restart.

What do you think?

**Comment by k-bx** [comment]
Actually, let me find the problem first. Replacing forkIO with fork didn't help seeing anything locally, server just stops on second gauge update.

**Comment by k-bx** [comment]
Ah. If I'd only look at response from json api I'd see "A web handler threw an exception: The name ""foo.bar"" is already taken by a metric.".

**Comment by tibbe** [comment]
I will make sure the exception is propagated from the thread to the main thread.

**Comment by tibbe** [comment]
Now fixed.

**Comment by k-bx** [comment]
Wonderful, thanks!
