### ISSUE TITLE
aeson 0.9 compatability

### ISSUE THREAD

**Issue by ghorn** [tibbe/ekg#44]
ekg compiles with aeson 0.9.0.1 (latest), but I haven't run it

aeson change log is here: http://hackage.haskell.org/package/aeson-0.9.0.1/changelog

**Comment by tibbe** [comment]
See #43.

**Comment by ghorn** [comment]
#43 is now merged, is anything blocking a hackage release?

**Comment by tibbe** [comment]
Released.
