### ISSUE TITLE
setBind causing problems with Docker based systems.

### ISSUE THREAD

**Issue by seanparsons** [tibbe/ekg#46]
It's taken me a while, but it appears this line:
https://github.com/tibbe/ekg/blob/f11d9311f4a9fe11946e2446e47068b331cfb257/System/Remote/Snap.hs#L65
Is causing ekg hosted within a Docker container to be inaccessible.

I'm still not entirely sure why this should be the case, but I reproduced it by creating a simple Snap service within my app and tried it both with and without setBind. Is it really necessary to bind to the numeric host of the hostname passed in, surely the default can be left as it is in this case?

**Comment by seanparsons** [comment]
As an aside the docker-haskell example snap app doesn't include that setting in the config and as such works perfectly: https://github.com/freebroccolo/docker-haskell/tree/master/examples/7.8/snap

**Comment by tibbe** [comment]
The reason for the `setBind` is security. Without it anyone on the network can connect to the ekg server and potentially sniff sensitive data from your app. Could it be that when connecting to docker the Snap server doesn't see the connection coming from localhost?

**Comment by seanparsons** [comment]
Surely it only restricts what network interfaces can be traversed to reach the ekg server? I think if it's necessary it would make more sense to expose it as a setting that can be configured, because as it is if that host resolves to more than one address it'll bind to the first randomly picked one based on the host. If anything as a result of not being exposed it violates the principle of least surprise, it's taken me 2 days of hitting on this to nail down the setBind as the cause.
