### ISSUE TITLE
Put "Required configuration" in the README

### ISSUE THREAD

**Issue by tomjaguarpaw** [tibbe/ekg#54]
Could you please put a "Required configuration" section in the `README`?  I spent a lot of time wondering why I wasn't collecting any statistics.  I didn't look at the `System.Remote.Monitoring` Haddock page because the `README` reads as though contains complete instructions.

**Comment by tomjaguarpaw** [comment]
(I'm talking specifically about the requirement to use `+RTS -T`.)

**Comment by tibbe** [comment]
Sounds like a good idea. Mind putting together a pull request?

**Comment by tomjaguarpaw** [comment]
Thanks, I'll do that.

**Comment by tomjaguarpaw** [comment]
Thanks.  Merged here: https://github.com/tibbe/ekg/pull/56
