### ISSUE TITLE
Fails to build on GHC8

### ISSUE THREAD

**Issue by tebello-thejane** [tibbe/ekg#59]
`ekg` fails to build on GHC8, due to bad dependencies (`snap-server` seems to be one culprit).

This is a terrible shame.

What can we do about it?

**Comment by tibbe** [comment]
Fix the deps in the cabal file and see if it works? :)

**Comment by tebello-thejane** [comment]
Unless `ekg` can somehow lose its dependency on the snap framework, I am not sure how to fix it. It's not a simple dependency change.

Please see https://github.com/snapframework/snap-core/issues/259

**Comment by tibbe** [comment]
I see. Lets give the snap devs a bit of time to make a new release. Removing the dependency on snap is something I want to do (to get something more lightweight), but I haven't found the time.

**Comment by tebello-thejane** [comment]
A new version of `snap` has been released, that builds on GHC8. I can also verify that `ekg` builds in a `cabal` running under GHC8 -- so `snap` is fixed. 

I THINK that the `stack` team will need to be alerted that `ekg` now builds on GHC8, so they can add it back to Stackage Nightly.

**Comment by 3noch** [comment]
This seems to be fixed now. True?
