### ISSUE TITLE
Don't rethrow ThreadKilled

### ISSUE THREAD

**Issue by neongreen** [tibbe/ekg#62]
Currently `ThreadKilled` seems to be rethrown along with all other exceptions:

``` haskell
forkServerWith store host port = do
    Metrics.registerCounter "ekg.server_timestamp_ms" getTimeMs store
    me <- myThreadId
    tid <- withSocketsDo $ forkFinally (startServer store host port) $ \ r ->
        case r of
            Left e  -> throwTo me e
            Right _ -> return ()
    return $! Server tid store
```

It means that when I try to kill EKG, it kills me in return, which is probably not the intended behavior.

**Comment by neongreen** [comment]
(Or perhaps I should just wrap EKG in a handler so that if EKG crashes by accident, it wouldn't crash the main thread?)

**Comment by tibbe** [comment]
I think we should change the code to not rethrow `ThreadKilled`. Mind putting together a pull request?

Even if you do that you might still want to be prepared to handle exceptions thrown to your thread by ekg.
