### ISSUE TITLE
How to remove the GC metrics?

### ISSUE THREAD

**Issue by dsorokin** [tibbe/ekg#65]
Is there a way to remove the GC metrics from the Web application? They are meaningless in my case. I would like to display only my own metrics. I can create a new Store, but the GC metrics still present in the GUI interface, because of which my metrics are not displayed on the chart

**Comment by tibbe** [comment]
Not currently. The JS code could probably be changed to detect the case of no GC metrics and not draw that part of the UI. I've got no time to work on this at the moment though. Patches welcome. :)

**Comment by dsorokin** [comment]
Thanks for the reply! I already understood it after looking at the sources. Probably, I will create a derived project or prepare a patch after I decide what namely monitoring facilities I need. I like your project.

Best regards,
David Sorokin
