### ISSUE TITLE
Build with ghc 8.4 (base-4.11)

### ISSUE THREAD

**Issue by DanBurton** [tibbe/ekg#70]
https://github.com/tibbe/ekg/blob/78a83736455460505e384eba42105e899827ef07/ekg.cabal#L43

**Comment by 23Skidoo** [comment]
I did a Hackage revision. Note that this also needs `snap-server-1.1`, which haven't been released yet.

**Comment by DanBurton** [comment]
@23Skidoo, the revision did not include relaxing the bound on `base` to `< 4.12`; could you revise again?

http://hackage.haskell.org/package/ekg-0.4.0.14/revisions/

**Comment by 23Skidoo** [comment]
Done.

**Comment by 23Skidoo** [comment]
In the meantime, new `snap-server` has been released.
