### ISSUE TITLE
How to stop or uninstall this service

### ISSUE THREAD

**Issue by Josema** [tibbe/ekg#72]
Hi, I think I installed this service installing dependencies for this project: https://github.com/input-output-hk/cardano-sl/blob/master/docs/how-to/build-cardano-sl-and-daedalus-from-source-code.md

But now with the port 8000 on the http protocol is always redirected this service. How can I stop that?

**Comment by 23Skidoo** [comment]
You're running some program that is using the `ekg` library. Since `ekg` is not a separate service, you need to stop the parent program or recompile it without `ekg` support. If you need further help, please file a ticket at the Cardano bug tracker.
