### ISSUE TITLE
Build and release with GHC 8.6.x

### ISSUE THREAD

**Issue by agourlay** [tibbe/ekg#74]
Thank you for the neat library 👍 

It would be great to have a release for GHC 8.6.x.

I am currently stuck on ekg 0.4.0.15 via the Stackage LTS 12.x

**Comment by 23Skidoo** [comment]
The latest version should work with GHC 8.6, see Travis.

**Comment by agourlay** [comment]
Thanks a lot for the quick answer 👍 

Then I guess my real problem is actually that it is not published on Stackage LTS 13.x.

Is it the right place to ask about it?

**Comment by 23Skidoo** [comment]
Try sending a bug report to the Stackage developers. 0.4.0.15 is the latest released `ekg` version, and it [works with GHC 8.6](https://matrix.hackage.haskell.org/#/package/ekg).
