### ISSUE TITLE
GHC 8.10 support

### ISSUE THREAD

**Issue by ejconlon** [tibbe/ekg#81]
Needs base upper bound bump. See https://github.com/commercialhaskell/stackage/issues/5365

**Comment by ejconlon** [comment]
Blocked on https://github.com/snapframework/snap-server/issues/128

**Comment by 23Skidoo** [comment]
Looks like a new release of snap is out, I bumped the bound on Hackage. Leaving open for now because I haven't updated CI yet.

**Comment by ejconlon** [comment]
I'll post a quick PR for that.
